# Generated by Django 4.1.3 on 2022-11-09 14:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, editable=False, help_text='Geographic coordinates (lon/lat) as Point. Can be serialised from WKT (well-known text) representation', null=True, srid=4326, verbose_name='last location'),
        ),
    ]
